// Add steps as necessary for accessing the software, post-configuration, and testing. Don’t include full usage instructions for your software, but add links to your product documentation for that information.
//Should any sections not be applicable, remove them

== Test the deployment
Once the stack has been successfully created, the *Outputs* tab shows the IP address of the Etleap instance, as well as the email and password you can use to log in.

[[best-practices-for-using-etleap-on-aws]]
== Best practices for using Etleap on AWS

Once logged in, the onboarding guide will help you get started with Etleap. For additional guidance and best practices, use the in-application link to the product documentation.

[[security]]
== Security

Etleap is accessed via HTTPS only, and it is recommended that you restrict the IP range in the _Etleap App_ EC2 Security Group for port 443 to just the IP addresses that you will use to access Etleap. Alternatively, you may launch the Etleap EC2 instance in a private subnet.

[[support]]
== Support

Etleap’s support team is standing by to assist you in configuring connections and operating your pipelines. Please reach out via in-application instant message or email support@etleap.com.